### ISSUE TITLE
Ore registry erros

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/BaseMetals#11]
Malisis Core by Ordinastie is apparently policing other mods. It reported that you have a few ore registry issues.

```
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorIron has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:64)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:65)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:66)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:67)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:68)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:69)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:70)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:71)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:72)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:73)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:74)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:75)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:76)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: ****************************************
[12:39:37] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name door has occurred. It adds an item (type: class net.malisis.doors.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Base Metals report it to them!
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:462)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:436)
[12:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:434)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.initVanillaRecipes(Recipes.java:77)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.init.Recipes.init(Recipes.java:30)
[12:39:37] [Client thread/WARN] [FML]: *  at cyano.basemetals.BaseMetals.init(BaseMetals.java:186)...
```

**Comment by DrPlantabyte** [comment]
Interesting. It is complaining about vanilla Minecraft items not being in the game registry (and apparently the Malisis core has replaced the vanilla doors with something else). I don't know if the game registry is just for mod items or if it is supposed to contain vanilla items, but the problem appears to be that the Malisis core has replaced the vanilla door items before Base Metals runs its init function, but doesn't get around to updating the game registry until after Base Metals has finished its initializing.

Maybe that's a bug in Malisis, but if it is not (or if Malisis insists that its my problem), then I need to know the order of initialization in Malisis core to fix this.

**Comment by kreezxil** [comment]
Those errors appear early in the console and don't appear to inhibit the game. Hopefully you and Ordinastie can figure things out.

-----Original Message-----

**Comment by DrPlantabyte** [comment]
I'll put an issue on the Malisis Doors mod asking for help.

**Comment by kreezxil** [comment]
Cool

-----Original Message-----

**Comment by kreezxil** [comment]
Left you a msg on Minecraft forum, completely unrelated to this... Did you get it?
